image: mcr.microsoft.com/playwright:v1.46.0-jammy

services:
  - docker:24.0.5-dind

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - test

before_script:
  - apt-get update
  - apt-get install -y docker-ce-cli
  - docker info

playwright:
  stage: test
  before_script:
    - git clone https://github.com/slawekradzyminski/awesome-localstack.git
    - cd awesome-localstack
    - chmod +x run-docker-compose-ci.sh
    - ./run-docker-compose-ci.sh
    - cd ..
  script:
    - npm ci
    - npx playwright install --with-deps
    - npx playwright test
  artifacts:
    when: always
    paths:
      - playwright-report/
    expire_in: 1 day