image: mcr.microsoft.com/playwright:v1.46.0-jammy

stages:
  - test

playwright:
  stage: test
  before_script:
    - echo "Starting LocalStack"
    - apt-get update && apt-get install -y git docker-compose
    - git clone https://github.com/slawekradzyminski/awesome-localstack.git
    - cd awesome-localstack
    - chmod +x run-docker-compose-ci.sh
    - ./run-docker-compose-ci.sh
    - cd ..
  script:
    - npm ci
    - npx playwright install --with-deps
    - npx playwright test
  artifacts:
    when: always
    paths:
      - playwright-report/
    expire_in: 1 day