image: mcr.microsoft.com/playwright:v1.47.1-noble

services:
  - docker:24.0.5-dind

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - test

before_script:
  - apt-get update && apt-get install -y git docker-compose

playwright:
  stage: test
  script:
    - git clone https://github.com/slawekradzyminski/awesome-localstack.git
    - cd awesome-localstack
    - chmod +x run-docker-compose-ci.sh
    - ./run-docker-compose-ci.sh
    - cd ..
    - docker info
    - npm ci
    - npx playwright test
  after_script:
    - cd awesome-localstack
    - docker-compose down
    - cd ..
  artifacts:
    when: always
    paths:
      - playwright-report/
    expire_in: 1 day